language: csharp

sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - libunwind8

matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest   

env:
  global:  
  - COMMIT=${TRAVIS_COMMIT::8}  
  - secure: "H5wkF2579efgwqXuduwoxyEVQP+GzKtTGA7sjgMkhkHdpKjnjB0g4MKjVjAaMuG1l4GOwqdVztv6U17yE49oWlO2MkAFe3ElMZsTt1DRb0djx5NEqmtyHFxiBCZ2aKD0Hl5jnQubqgknKS5sOwOQtktT5amIl6+LdgXWEfDXEJ0RdSOr3/DzaXbn/cMsZa9IVZFa0lSU+GMmC4Y7RmjGDlj/0i3GdrKJ6poOXX5H37x0isfTndCmzX7guKdFpZCK4aMrc99XoSxqLPrGMumpjm1lP1N79F8N4h3iYjEa/GAPTIqVcJOv5uRmAcmLrjm1Jb2QrrpUh7sUWovgMJ0il/LVMWu+5rvy4QZ+GMSSkOWBNue0JoCNTUUauXoS5YWUAU9pWnZJOp6n2p53o6rb0j530HhBmQdGIE7rWVwO23tajbNiPNEiFEe6M9ZQ5hhWxE8pCqSzcS8x7uWxAp6Q42JwO2tYi9GYpVr+G8rKYyoyBpqlDql7EdAqetz/X4Y1jHW4ATIpZE9ldFHzEwt29aAeXB91yA8dIoPdfGr8idzQn5i/9XQ9esKM9siTQtdqP23RYo2uA3CFmOEyJc32kEsgg+dtJ2SITiU6z1W+kZoQ5M+HE5ialtP0wp1ooSlZPV3iv1zXaiGclpwAdXUXo8uHNOz4oJvPth/Y6z0RJCM="

install:
  - npm install semver -g
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh | bash /dev/stdin --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull dockerfile/elasticsearch; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -d -p 9200:9200 -p 9300:9300 dockerfile/elasticsearch; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker ps; fi
  - chmod u+x build.sh
  - chmod u+x ./scripts/set-build-version.sh
  - chmod u+x ./scripts/patch-version.sh
  - chmod u+x ./scripts/push-to-nuget.sh
  - eval $(./scripts/set-build-version.sh)
  - ./scripts/patch-version.sh --version=$PROJECT_BUILD_VERSION
  - export PATH=$PATH:$HOME/.local/bin
  - dotnet --info

script:
  - ./build.sh --version=$PROJECT_BUILD_VERSION --configuration=Release --pack

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [ ! -z "$TRAVIS_TAG" ] && semver $TRAVIS_TAG &>/dev/null; then ./scripts/push-to-nuget.sh --apikey=$NUGET_API_KEY --version=$PROJECT_BUILD_VERSION; fi