environment:  
  DOTNET_INSTALL_DIR: .\dotnetcli
  ASPNETCORE_ENVIRONMENT: AppVeyor

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: 27ed618d-1d4f-440b-a094-a99f2e34a14b
  skip_symbols: false
  #symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: '**\*.nupkg'

build_script:
  # Download and install .NET Core SDK
  - ps: (new-object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1", "$PWD\dotnet.ps1")
  - ps: dir
  - ps: .\dotnet.ps1 -InstallDir $env:DOTNET_INSTALL_DIR
  # Download and run local DynamoDB
  - ps: Start-Process -NoNewWindow powershell .\scripts\local_db.ps1
  # Restore, build, test
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build .\src\AspNetCore.Identity.ElasticSearch -c Release
  - ps: dotnet build .\sample -c Release
  - ps: dotnet build .\tests\AspNetCore.Identity.ElasticSearch.Tests -c Release
  - ps: dotnet test .\tests\AspNetCore.Identity.ElasticSearch.Tests\AspNetCore.Identity.ElasticSearch.Tests.csproj -c Release --no-build

test: off
version: '0.0.0.{build}'